# STEP 1: Base image
FROM python:3.12-slim

# STEP 2: Set working directory inside the container
WORKDIR /app

# STEP 3: Copy requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# STEP 4: Copy frontend code into container
COPY ./src ./src

# STEP 5: Expose frontend port
EXPOSE 8501

# STEP 6: Run Streamlit app
CMD ["streamlit", "run", "src/streamlit_app.py", "--server.address", "0.0.0.0", "--server.port", "8501"]
